# Generated by Django 5.0.6 on 2025-03-22 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="booking",
            name="time",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
