# Generated by Django 5.0.6 on 2025-03-23 06:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_fileaccessrequest_otpverification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpverification",
            name="user",
        ),
        migrations.DeleteModel(
            name="FileAccessRequest",
        ),
        migrations.DeleteModel(
            name="OTPVerification",
        ),
    ]
