# Generated by Django 5.0.6 on 2025-03-23 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0004_otprequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTPRequest",
        ),
    ]
