# Generated by Django 5.1.7 on 2025-03-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
    ]
