# Generated by Django 5.1.7 on 2025-03-20 18:04

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20250320_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to=reports.models.user_report_path),
        ),
    ]
