# Generated by Django 5.1.7 on 2025-03-22 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_phone_number_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HealthParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('parameter_name', models.CharField(max_length=100)),
                ('parameter_value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('recorded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='reports.report')),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number', 'parameter_name'], name='reports_hea_phone_n_49f711_idx')],
                'unique_together': {('report', 'parameter_name')},
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='reports.report')),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number'], name='reports_res_phone_n_2373fd_idx')],
            },
        ),
    ]
